version: "3.9"

services:
  db:
    image: postgres:14.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    env_file:
      ./url_shortener/.env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
  backend:
    build: .
    command: bash -c "export environment=docker.env && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    env_file:
      ./url_shortener/.env
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
    postgres_data: