# Generated by Django 4.1.7 on 2023-03-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="url",
            name="short_url",
        ),
        migrations.AddField(
            model_name="url",
            name="short_url_id",
            field=models.CharField(default="947cd5", max_length=11, unique=True),
        ),
    ]
